import React from 'react';
import styled from 'styled-components';
import icons from './mdi-icons.json';
import { scale } from './tokens.js';

/**
 * Inline Material Design Icons (https://icon-sets.iconify.design/mdi/).
 *
 * Icon paths are vendored in `mdi-icons.json` (generated by
 * `mise run icons`) rather than fetched from the Iconify API, because the
 * theme is rendered server-side by Bun and then turned into a PDF by
 * WeasyPrint — neither should depend on network access.
 *
 * Icons are monotone with fill="currentColor", so they inherit the colour of
 * the surrounding text.
 */

const Svg = styled.svg`
  display: inline-block;
  width: 1em;
  height: 1em;
  margin-right: ${scale(5)};
  vertical-align: -0.15em;
`;

/** Map a profile network name onto a vendored icon key. */
export const networkIcon = (network) => {
  const key = (network || '').toLowerCase();
  return icons.icons[key] ? key : 'website';
};

export const Icon = ({ name, className }) => {
  const icon = icons.icons[name];
  if (!icon) return null;
  return (
    <Svg
      className={className}
      xmlns="http://www.w3.org/2000/svg"
      viewBox={`0 0 ${icons.width} ${icons.height}`}
      aria-hidden="true"
      focusable="false"
      dangerouslySetInnerHTML={{ __html: icon.body }}
    />
  );
};

export default Icon;
